name: Smoke Test - P2P

on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run smokeStage:P2P script
        run: npm run smokeStage:P2P

      - name: Show cucumber_report.json content (debug)
        run: type report\cucumber_report.json

      - name: Run reporter.js to generate HTML report
        run: node reporter.js

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-html-report
          path: C:/Users/ADMIN/Documents/Personal_Git/Test_DemoProject123-/report/html_report
