name: Smoke Test - P2P

on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run smokeStage:P2P script
        run: npm run smokeStage:P2P

      - name: Debug – list report folder after test
        run: dir report

      - name: Debug – check TestData.json presence
        run: dir features\support\Testdata

      - name: Run reporter
        run: npm run reporter

      - name: Debug – list html_report directory
        continue-on-error: true
        run: dir report\html_report

      - name: Upload test report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-report
          path: report/html_report/
